stages:
  - deploy

variables:
  ANSIBLE_FORCE_COLOR: 'true'

deploy_production:
  stage: deploy
  tags:
    - my-runner
  script:
    - cd ansible
    # Создаем временный файл инвентаря для локального запуска
    - echo "[normocontrol]" > inventory_ci.ini
    - echo "localhost ansible_connection=local" >> inventory_ci.ini
    
    # Запускаем деплой. Теперь он идет прямо внутри вашего сервера!
    - ansible-playbook -i inventory_ci.ini deploy.yml \
      --extra-vars "gemini_api_key=$GEMINI_API_KEY jwt_secret=$JWT_SECRET allowed_origin=$ALLOWED_ORIGIN"
  only:
    - main
  environment:
    name: production
    url: https://normo-control.ru
